# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'chronos', '0002_auto_20181004_0223'), (b'chronos', '0003_auto_20181004_0317'), (b'chronos', '0004_auto_20181005_0031')]

    dependencies = [
        ('chronos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=b'old', unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='href',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='href',
            field=models.URLField(blank=True, null=True, verbose_name=b'link'),
        ),
    ]
