# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chronos', '0003_auto_20181004_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField()),
                ('title', models.CharField(max_length=400)),
                ('alt', models.TextField()),
                ('groups', models.ManyToManyField(to='chronos.Album')),
            ],
        ),
    ]
