# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default='old', unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.URLField(verbose_name='link'),
        ),
    ]
